# Generated by Django 2.2.7 on 2019-12-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_image', models.ImageField(null=True, upload_to='media/images/')),
            ],
        ),
    ]
